=== alanapz/frtest/app/src/main/resources/verbs.dtd
<?xml version='1.0' encoding='UTF-8'?>
<!ELEMENT dictionary (verbs)*>
<!ELEMENT verbs (verb)*>
<!ELEMENT verb (infinitive, hAspire?, translation*, transitive?, irregular?, takesEtreInPerfect?, spellingChange?, stemChange?, presentParticiple?, pastParticiple?, pronominal?, present?, imperative?, imperfect?, future?, subjunctive?, conditional?)>
<!ELEMENT infinitive (#PCDATA)>
<!ELEMENT hAspire EMPTY>
<!ELEMENT translation (#PCDATA)>
<!ELEMENT transitive EMPTY>
<!ELEMENT important EMPTY>
<!ELEMENT commonplace EMPTY>
<!ELEMENT irregular EMPTY>
<!ELEMENT takesEtreInPerfect EMPTY>
<!ELEMENT spellingChange EMPTY>
<!ELEMENT stemChange EMPTY>
<!ELEMENT presentParticiple (#PCDATA)>
<!ELEMENT pastParticiple (#PCDATA)>
<!ELEMENT pronominal (translation+)>
<!ELEMENT present (je, tu, il, nous, vous, ils)>
<!ELEMENT imperative (tu, nous, vous)>
<!ELEMENT imperfect (je, tu, il, nous, vous, ils)>
<!ELEMENT future (je, tu, il, nous, vous, ils)>
<!ELEMENT subjunctive (je, tu, il, nous, vous, ils)>
<!ELEMENT conditional (je, tu, il, nous, vous, ils)>
<!ELEMENT je (#PCDATA)>
<!ELEMENT tu (#PCDATA)>
<!ELEMENT il (#PCDATA)>
<!ELEMENT nous (#PCDATA)>
<!ELEMENT vous (#PCDATA)>
<!ELEMENT ils (#PCDATA)>

=== alanapz/frtest/db/verbs/Choquer.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE dictionary SYSTEM "verbs.dtd">
<dictionary>
<verbs>
<verb>
	<infinitive>choquer</infinitive>
	<translation>to shock</translation>
	<translation>appall</translation>
	<translation>to shake up</translation>
	<presentParticiple>choquant</presentParticiple>
	<pastParticiple>choqu√©</pastParticiple>
	<present>
		<je>choque</je>
		<tu>choques</tu>
		<il>choque</il>
		<nous>choquons</nous>
		<vous>choquez</vous>
		<ils>choquent</ils>
	</present>
	<imperative>
		<tu>choque</tu>
		<nous>choquons</nous>
		<vous>choquez</vous>
	</imperative>
	<imperfect>
		<je>choquais</je>
		<tu>choquais</tu>
		<il>choquait</il>
		<nous>choquions</nous>
		<vous>choquiez</vous>
		<ils>choquaient</ils>
	</imperfect>
	<future>
		<je>choquerai</je>
		<tu>choqueras</tu>
		<il>choquera</il>
		<nous>choquerons</nous>
		<vous>choquerez</vous>
		<ils>choqueront</ils>
	</future>
	<subjunctive>
		<je>choque</je>
		<tu>choques</tu>
		<il>choque</il>
		<nous>choquions</nous>
		<vous>choquiez</vous>
		<ils>choquent</ils>
	</subjunctive>
	<conditional>
		<je>choquerais</je>
		<tu>choquerais</tu>
		<il>choquerait</il>
		<nous>choquerions</nous>
		<vous>choqueriez</vous>
		<ils>choqueraient</ils>
	</conditional>
</verb>
</verbs>
</dictionary>

=== alanapz/frtest/db/verbs/Warranter.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE dictionary SYSTEM "verbs.dtd">
<dictionary>
<verbs>
<verb>
	<infinitive>warranter</infinitive>
	<translation>to warrant</translation>
	<presentParticiple>warrantant</presentParticiple>
	<pastParticiple>warrantÃ©</pastParticiple>
	<present>
		<je>warrante</je>
		<tu>warrantes</tu>
		<il>warrante</il>
		<nous>warrantons</nous>
		<vous>warrantez</vous>
		<ils>warrantent</ils>
	</present>
	<imperative>
		<tu>warrante</tu>
		<nous>warrantons</nous>
		<vous>warrantez</vous>
	</imperative>
	<imperfect>
		<je>warrantais</je>
		<tu>warrantais</tu>
		<il>warrantait</il>
		<nous>warrantions</nous>
		<vous>warrantiez</vous>
		<ils>warrantaient</ils>
	</imperfect>
	<future>
		<je>warranterai</je>
		<tu>warranteras</tu>
		<il>warrantera</il>
		<nous>warranterons</nous>
		<vous>warranterez</vous>
		<ils>warranteront</ils>
	</future>
	<subjunctive>
		<je>warrante</je>
		<tu>warrantes</tu>
		<il>warrante</il>
		<nous>warrantions</nous>
		<vous>warrantiez</vous>
		<ils>warrantent</ils>
	</subjunctive>
	<conditional>
		<je>warranterais</je>
		<tu>warranterais</tu>
		<il>warranterait</il>
		<nous>warranterions</nous>
		<vous>warranteriez</vous>
		<ils>warranteraient</ils>
	</conditional>
</verb>
</verbs>
</dictionary>

=== alanapz/frtest/db/verbs/Décrire.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE dictionary SYSTEM "verbs.dtd">
<dictionary>
<verbs>
<verb>
	<infinitive>décrire</infinitive>
	<translation>to describe</translation>
	<irregular />
	<presentParticiple>décrivant</presentParticiple>
	<pastParticiple>décrit</pastParticiple>
	<present>
		<je>décris</je>
		<tu>décris</tu>
		<il>décrit</il>
		<nous>décrivons</nous>
		<vous>décrivez</vous>
		<ils>décrivent</ils>
	</present>
	<imperative>
		<tu>décris</tu>
		<nous>décrivons</nous>
		<vous>décrivez</vous>
	</imperative>
	<imperfect>
		<je>décrivais</je>
		<tu>décrivais</tu>
		<il>décrivait</il>
		<nous>décrivions</nous>
		<vous>décriviez</vous>
		<ils>décrivaient</ils>
	</imperfect>
	<future>
		<je>décrirai</je>
		<tu>décriras</tu>
		<il>décrira</il>
		<nous>décrirons</nous>
		<vous>décrirez</vous>
		<ils>décriront</ils>
	</future>
	<subjunctive>
		<je>décrive</je>
		<tu>décrives</tu>
		<il>décrive</il>
		<nous>décrivions</nous>
		<vous>décriviez</vous>
		<ils>décrivent</ils>
	</subjunctive>
	<conditional>
		<je>décrirais</je>
		<tu>décrirais</tu>
		<il>décrirait</il>
		<nous>décririons</nous>
		<vous>décririez</vous>
		<ils>décriraient</ils>
	</conditional>
</verb>
</verbs>
</dictionary>

=== alanapz/frtest/db/verbs/Vendre.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE dictionary SYSTEM "verbs.dtd">
<dictionary>
<verbs>
<verb>
	<infinitive>vendre</infinitive>
	<translation>to sell</translation>
	<presentParticiple>vendant</presentParticiple>
	<pastParticiple>vendu</pastParticiple>
	<present>
		<je>vends</je>
		<tu>vends</tu>
		<il>vend</il>
		<nous>vendons</nous>
		<vous>vendez</vous>
		<ils>vendent</ils>
	</present>
	<imperative>
		<tu>vends</tu>
		<nous>vendons</nous>
		<vous>vendez</vous>
	</imperative>
	<imperfect>
		<je>vendais</je>
		<tu>vendais</tu>
		<il>vendait</il>
		<nous>vendions</nous>
		<vous>vendiez</vous>
		<ils>vendaient</ils>
	</imperfect>
	<future>
		<je>vendrai</je>
		<tu>vendras</tu>
		<il>vendra</il>
		<nous>vendrons</nous>
		<vous>vendrez</vous>
		<ils>vendront</ils>
	</future>
	<subjunctive>
		<je>vende</je>
		<tu>vendes</tu>
		<il>vende</il>
		<nous>vendions</nous>
		<vous>vendiez</vous>
		<ils>vendent</ils>
	</subjunctive>
	<conditional>
		<je>vendrais</je>
		<tu>vendrais</tu>
		<il>vendrait</il>
		<nous>vendrions</nous>
		<vous>vendriez</vous>
		<ils>vendraient</ils>
	</conditional>
</verb>
</verbs>
</dictionary>

=== alanapz/frtest/db/verbs/Marquer.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE dictionary SYSTEM "verbs.dtd">
<dictionary>
<verbs>
<verb>
	<infinitive>marquer</infinitive>
	<translation>to mark</translation>
	<translation>indicate</translation>
	<presentParticiple>marquant</presentParticiple>
	<pastParticiple>marqu√©</pastParticiple>
	<present>
		<je>marque</je>
		<tu>marques</tu>
		<il>marque</il>
		<nous>marquons</nous>
		<vous>marquez</vous>
		<ils>marquent</ils>
	</present>
	<imperative>
		<tu>marque</tu>
		<nous>marquons</nous>
		<vous>marquez</vous>
	</imperative>
	<imperfect>
		<je>marquais</je>
		<tu>marquais</tu>
		<il>marquait</il>
		<nous>marquions</nous>
		<vous>marquiez</vous>
		<ils>marquaient</ils>
	</imperfect>
	<future>
		<je>marquerai</je>
		<tu>marqueras</tu>
		<il>marquera</il>
		<nous>marquerons</nous>
		<vous>marquerez</vous>
		<ils>marqueront</ils>
	</future>
	<subjunctive>
		<je>marque</je>
		<tu>marques</tu>
		<il>marque</il>
		<nous>marquions</nous>
		<vous>marquiez</vous>
		<ils>marquent</ils>
	</subjunctive>
	<conditional>
		<je>marquerais</je>
		<tu>marquerais</tu>
		<il>marquerait</il>
		<nous>marquerions</nous>
		<vous>marqueriez</vous>
		<ils>marqueraient</ils>
	</conditional>
</verb>
</verbs>
</dictionary>

=== alanapz/frtest/db/verbs/Remplir.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE dictionary SYSTEM "verbs.dtd">
<dictionary>
    <verbs>
        <verb>
            <infinitive>remplir</infinitive>
            <translation>to fill</translation>
            <presentParticiple>remplissant</presentParticiple>
            <pastParticiple>rempli</pastParticiple>
            <present>
                <je>remplis</je>
                <tu>remplis</tu>
                <il>remplit</il>
                <nous>remplissons</nous>
                <vous>remplissez</vous>
                <ils>remplissent</ils>
            </present>
            <imperative>
                <tu>remplis</tu>
                <nous>remplissons</nous>
                <vous>remplissez</vous>
            </imperative>
            <imperfect>
                <je>remplissais</je>
                <tu>remplissais</tu>
                <il>remplissait</il>
                <nous>remplissions</nous>
                <vous>remplissiez</vous>
                <ils>remplissaient</ils>
            </imperfect>
            <future>
                <je>remplirai</je>
                <tu>rempliras</tu>
                <il>remplira</il>
                <nous>remplirons</nous>
                <vous>remplirez</vous>
                <ils>rempliront</ils>
            </future>
            <subjunctive>
                <je>remplisse</je>
                <tu>remplisses</tu>
                <il>remplisse</il>
                <nous>remplissions</nous>
                <vous>remplissiez</vous>
                <ils>remplissent</ils>
            </subjunctive>
            <conditional>
                <je>remplirais</je>
                <tu>remplirais</tu>
                <il>remplirait</il>
                <nous>remplirions</nous>
                <vous>rempliriez</vous>
                <ils>rempliraient</ils>
            </conditional>
        </verb>
    </verbs>
</dictionary>

=== alanapz/frtest/db/verbs/Instruire.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE dictionary SYSTEM "verbs.dtd">
<dictionary>
<verbs>
<verb>
	<infinitive>instruire</infinitive>
	<translation>to instruct</translation>
	<irregular />
	<presentParticiple>instruisant</presentParticiple>
	<pastParticiple>instruit</pastParticiple>
	<present>
		<je>instruis</je>
		<tu>instruis</tu>
		<il>instruit</il>
		<nous>instruisons</nous>
		<vous>instruisez</vous>
		<ils>instruisent</ils>
	</present>
	<imperative>
		<tu>instruis</tu>
		<nous>instruisons</nous>
		<vous>instruisez</vous>
	</imperative>
	<imperfect>
		<je>instruisais</je>
		<tu>instruisais</tu>
		<il>instruisait</il>
		<nous>instruisions</nous>
		<vous>instruisiez</vous>
		<ils>instruisaient</ils>
	</imperfect>
	<future>
		<je>instruirai</je>
		<tu>instruiras</tu>
		<il>instruira</il>
		<nous>instruirons</nous>
		<vous>instruirez</vous>
		<ils>instruiront</ils>
	</future>
	<subjunctive>
		<je>instruise</je>
		<tu>instruises</tu>
		<il>instruise</il>
		<nous>instruisions</nous>
		<vous>instruisiez</vous>
		<ils>instruisent</ils>
	</subjunctive>
	<conditional>
		<je>instruirais</je>
		<tu>instruirais</tu>
		<il>instruirait</il>
		<nous>instruirions</nous>
		<vous>instruiriez</vous>
		<ils>instruiraient</ils>
	</conditional>
</verb>
</verbs>
</dictionary>

=== alanapz/frtest/db/verbs/Emporter.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE dictionary SYSTEM "verbs.dtd">
<dictionary>
<verbs>
<verb>
	<infinitive>emporter</infinitive>
	<translation>to take</translation>
	<presentParticiple>emportant</presentParticiple>
	<pastParticiple>emport√©</pastParticiple>
	<present>
		<je>emporte</je>
		<tu>emportes</tu>
		<il>emporte</il>
		<nous>emportons</nous>
		<vous>emportez</vous>
		<ils>emportent</ils>
	</present>
	<imperative>
		<tu>emporte</tu>
		<nous>emportons</nous>
		<vous>emportez</vous>
	</imperative>
	<imperfect>
		<je>emportais</je>
		<tu>emportais</tu>
		<il>emportait</il>
		<nous>emportions</nous>
		<vous>emportiez</vous>
		<ils>emportaient</ils>
	</imperfect>
	<future>
		<je>emporterai</je>
		<tu>emporteras</tu>
		<il>emportera</il>
		<nous>emporterons</nous>
		<vous>emporterez</vous>
		<ils>emporteront</ils>
	</future>
	<subjunctive>
		<je>emporte</je>
		<tu>emportes</tu>
		<il>emporte</il>
		<nous>emportions</nous>
		<vous>emportiez</vous>
		<ils>emportent</ils>
	</subjunctive>
	<conditional>
		<je>emporterais</je>
		<tu>emporterais</tu>
		<il>emporterait</il>
		<nous>emporterions</nous>
		<vous>emporteriez</vous>
		<ils>emporteraient</ils>
	</conditional>
</verb>
</verbs>
</dictionary>
