=== alanapz/frtest/app/src/main/resources/verbs.dtd
<?xml version='1.0' encoding='UTF-8'?>
<!ELEMENT dictionary (verbs)*>
<!ELEMENT verbs (verb)*>
<!ELEMENT verb (infinitive, hAspire?, translation*, transitive?, irregular?, takesEtreInPerfect?, spellingChange?, stemChange?, presentParticiple?, pastParticiple?, pronominal?, present?, imperative?, imperfect?, future?, subjunctive?, conditional?)>
<!ELEMENT infinitive (#PCDATA)>
<!ELEMENT hAspire EMPTY>
<!ELEMENT translation (#PCDATA)>
<!ELEMENT transitive EMPTY>
<!ELEMENT important EMPTY>
<!ELEMENT commonplace EMPTY>
<!ELEMENT irregular EMPTY>
<!ELEMENT takesEtreInPerfect EMPTY>
<!ELEMENT spellingChange EMPTY>
<!ELEMENT stemChange EMPTY>
<!ELEMENT presentParticiple (#PCDATA)>
<!ELEMENT pastParticiple (#PCDATA)>
<!ELEMENT pronominal (translation+)>
<!ELEMENT present (je, tu, il, nous, vous, ils)>
<!ELEMENT imperative (tu, nous, vous)>
<!ELEMENT imperfect (je, tu, il, nous, vous, ils)>
<!ELEMENT future (je, tu, il, nous, vous, ils)>
<!ELEMENT subjunctive (je, tu, il, nous, vous, ils)>
<!ELEMENT conditional (je, tu, il, nous, vous, ils)>
<!ELEMENT je (#PCDATA)>
<!ELEMENT tu (#PCDATA)>
<!ELEMENT il (#PCDATA)>
<!ELEMENT nous (#PCDATA)>
<!ELEMENT vous (#PCDATA)>
<!ELEMENT ils (#PCDATA)>

=== alanapz/frtest/db/verbs/Convaincre.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE dictionary SYSTEM "verbs.dtd">
<dictionary>
<verbs>
<verb>
	<infinitive>convaincre</infinitive>
	<translation>to convince</translation>
	<irregular />
	<presentParticiple>convainquant</presentParticiple>
	<pastParticiple>convaincu</pastParticiple>
	<present>
		<je>convaincs</je>
		<tu>convaincs</tu>
		<il>convainc</il>
		<nous>convainquons</nous>
		<vous>convainquez</vous>
		<ils>convainquent</ils>
	</present>
	<imperative>
		<tu>convaincs</tu>
		<nous>convainquons</nous>
		<vous>convainquez</vous>
	</imperative>
	<imperfect>
		<je>convainquais</je>
		<tu>convainquais</tu>
		<il>convainquait</il>
		<nous>convainquions</nous>
		<vous>convainquiez</vous>
		<ils>convainquaient</ils>
	</imperfect>
	<future>
		<je>convaincrai</je>
		<tu>convaincras</tu>
		<il>convaincra</il>
		<nous>convaincrons</nous>
		<vous>convaincrez</vous>
		<ils>convaincront</ils>
	</future>
	<subjunctive>
		<je>convainque</je>
		<tu>convainques</tu>
		<il>convainque</il>
		<nous>convainquions</nous>
		<vous>convainquiez</vous>
		<ils>convainquent</ils>
	</subjunctive>
	<conditional>
		<je>convaincrais</je>
		<tu>convaincrais</tu>
		<il>convaincrait</il>
		<nous>convaincrions</nous>
		<vous>convaincriez</vous>
		<ils>convaincraient</ils>
	</conditional>
</verb>
</verbs>
</dictionary>

=== alanapz/frtest/db/verbs/Emprunter.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE dictionary SYSTEM "verbs.dtd">
<dictionary>
<verbs>
<verb>
	<infinitive>emprunter</infinitive>
	<translation>to borrow</translation>
	<presentParticiple>empruntant</presentParticiple>
	<pastParticiple>emprunt√©</pastParticiple>
	<present>
		<je>emprunte</je>
		<tu>empruntes</tu>
		<il>emprunte</il>
		<nous>empruntons</nous>
		<vous>empruntez</vous>
		<ils>empruntent</ils>
	</present>
	<imperative>
		<tu>emprunte</tu>
		<nous>empruntons</nous>
		<vous>empruntez</vous>
	</imperative>
	<imperfect>
		<je>empruntais</je>
		<tu>empruntais</tu>
		<il>empruntait</il>
		<nous>empruntions</nous>
		<vous>empruntiez</vous>
		<ils>empruntaient</ils>
	</imperfect>
	<future>
		<je>emprunterai</je>
		<tu>emprunteras</tu>
		<il>empruntera</il>
		<nous>emprunterons</nous>
		<vous>emprunterez</vous>
		<ils>emprunteront</ils>
	</future>
	<subjunctive>
		<je>emprunte</je>
		<tu>empruntes</tu>
		<il>emprunte</il>
		<nous>empruntions</nous>
		<vous>empruntiez</vous>
		<ils>empruntent</ils>
	</subjunctive>
	<conditional>
		<je>emprunterais</je>
		<tu>emprunterais</tu>
		<il>emprunterait</il>
		<nous>emprunterions</nous>
		<vous>emprunteriez</vous>
		<ils>emprunteraient</ils>
	</conditional>
</verb>
</verbs>
</dictionary>

=== alanapz/frtest/db/verbs/Surprendre.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE dictionary SYSTEM "verbs.dtd">
<dictionary>
<verbs>
<verb>
	<infinitive>surprendre</infinitive>
	<translation>to surprise</translation>
	<irregular />
	<presentParticiple>surprenant</presentParticiple>
	<pastParticiple>surpris</pastParticiple>
	<present>
		<je>surprends</je>
		<tu>surprends</tu>
		<il>surprend</il>
		<nous>surprenons</nous>
		<vous>surprenez</vous>
		<ils>surprennent</ils>
	</present>
	<imperative>
		<tu>surprends</tu>
		<nous>surprenons</nous>
		<vous>surprenez</vous>
	</imperative>
	<imperfect>
		<je>surprenais</je>
		<tu>surprenais</tu>
		<il>surprenait</il>
		<nous>surprenions</nous>
		<vous>surpreniez</vous>
		<ils>surprenaient</ils>
	</imperfect>
	<future>
		<je>surprendrai</je>
		<tu>surprendras</tu>
		<il>surprendra</il>
		<nous>surprendrons</nous>
		<vous>surprendrez</vous>
		<ils>surprendront</ils>
	</future>
	<subjunctive>
		<je>surprenne</je>
		<tu>surprennes</tu>
		<il>surprenne</il>
		<nous>surprenions</nous>
		<vous>surpreniez</vous>
		<ils>surprennent</ils>
	</subjunctive>
	<conditional>
		<je>surprendrais</je>
		<tu>surprendrais</tu>
		<il>surprendrait</il>
		<nous>surprendrions</nous>
		<vous>surprendriez</vous>
		<ils>surprendraient</ils>
	</conditional>
</verb>
</verbs>
</dictionary>

=== alanapz/frtest/db/verbs/Changer.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE dictionary SYSTEM "verbs.dtd">
<dictionary>
<verbs>
<verb>
	<infinitive>changer</infinitive>
	<translation>to change</translation>
	<spellingChange />
	<presentParticiple>changeant</presentParticiple>
	<pastParticiple>changÃ©</pastParticiple>
	<present>
		<je>change</je>
		<tu>changes</tu>
		<il>change</il>
		<nous>changeons</nous>
		<vous>changez</vous>
		<ils>changent</ils>
	</present>
	<imperative>
		<tu>change</tu>
		<nous>changeons</nous>
		<vous>changez</vous>
	</imperative>
	<imperfect>
		<je>changeais</je>
		<tu>changeais</tu>
		<il>changeait</il>
		<nous>changions</nous>
		<vous>changiez</vous>
		<ils>changeaient</ils>
	</imperfect>
	<future>
		<je>changerai</je>
		<tu>changeras</tu>
		<il>changera</il>
		<nous>changerons</nous>
		<vous>changerez</vous>
		<ils>changeront</ils>
	</future>
	<subjunctive>
		<je>change</je>
		<tu>changes</tu>
		<il>change</il>
		<nous>changions</nous>
		<vous>changiez</vous>
		<ils>changent</ils>
	</subjunctive>
	<conditional>
		<je>changerais</je>
		<tu>changerais</tu>
		<il>changerait</il>
		<nous>changerions</nous>
		<vous>changeriez</vous>
		<ils>changeraient</ils>
	</conditional>
</verb>
</verbs>
</dictionary>

=== alanapz/frtest/db/verbs/Retrouver.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE dictionary SYSTEM "verbs.dtd">
<dictionary>
    <verbs>
        <verb>
            <infinitive>retrouver</infinitive>
            <translation>to re-find</translation>
            <presentParticiple>retrouvant</presentParticiple>
            <pastParticiple>retrouvÃ©</pastParticiple>
            <present>
                <je>retrouve</je>
                <tu>retrouves</tu>
                <il>retrouve</il>
                <nous>retrouvons</nous>
                <vous>retrouvez</vous>
                <ils>retrouvent</ils>
            </present>
            <imperative>
                <tu>retrouve</tu>
                <nous>retrouvons</nous>
                <vous>retrouvez</vous>
            </imperative>
            <imperfect>
                <je>retrouvais</je>
                <tu>retrouvais</tu>
                <il>retrouvait</il>
                <nous>retrouvions</nous>
                <vous>retrouviez</vous>
                <ils>retrouvaient</ils>
            </imperfect>
            <future>
                <je>retrouverai</je>
                <tu>retrouveras</tu>
                <il>retrouvera</il>
                <nous>retrouverons</nous>
                <vous>retrouverez</vous>
                <ils>retrouveront</ils>
            </future>
            <subjunctive>
                <je>retrouve</je>
                <tu>retrouves</tu>
                <il>retrouve</il>
                <nous>retrouvions</nous>
                <vous>retrouviez</vous>
                <ils>retrouvent</ils>
            </subjunctive>
            <conditional>
                <je>retrouverais</je>
                <tu>retrouverais</tu>
                <il>retrouverait</il>
                <nous>retrouverions</nous>
                <vous>retrouveriez</vous>
                <ils>retrouveraient</ils>
            </conditional>
        </verb>
    </verbs>
</dictionary>

=== alanapz/frtest/db/verbs/Défaire.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE dictionary SYSTEM "verbs.dtd">
<dictionary>
<verbs>
<verb>
	<infinitive>défaire</infinitive>
	<translation>to undo</translation>
	<translation>dismantle</translation>
	<irregular />
	<presentParticiple>défaisant</presentParticiple>
	<pastParticiple>défait</pastParticiple>
	<present>
		<je>défais</je>
		<tu>défais</tu>
		<il>défait</il>
		<nous>défaisons</nous>
		<vous>défaites</vous>
		<ils>défont</ils>
	</present>
	<imperative>
		<tu>défais</tu>
		<nous>défaisons</nous>
		<vous>défaites</vous>
	</imperative>
	<imperfect>
		<je>défaisais</je>
		<tu>défaisais</tu>
		<il>défaisait</il>
		<nous>défaisions</nous>
		<vous>défaisiez</vous>
		<ils>défaisaient</ils>
	</imperfect>
	<future>
		<je>déferai</je>
		<tu>déferas</tu>
		<il>défera</il>
		<nous>déferons</nous>
		<vous>déferez</vous>
		<ils>déferont</ils>
	</future>
	<subjunctive>
		<je>défasse</je>
		<tu>défasses</tu>
		<il>défasse</il>
		<nous>défassions</nous>
		<vous>défassiez</vous>
		<ils>défassent</ils>
	</subjunctive>
	<conditional>
		<je>déferais</je>
		<tu>déferais</tu>
		<il>déferait</il>
		<nous>déferions</nous>
		<vous>déferiez</vous>
		<ils>déferaient</ils>
	</conditional>
</verb>
</verbs>
</dictionary>

=== alanapz/frtest/db/verbs/Regretter.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE dictionary SYSTEM "verbs.dtd">
<dictionary>
    <verbs>
        <verb>
            <infinitive>regretter</infinitive>
            <translation>to regret</translation>
            <presentParticiple>regrettant</presentParticiple>
            <pastParticiple>regrettÃ©</pastParticiple>
            <present>
                <je>regrette</je>
                <tu>regrettes</tu>
                <il>regrette</il>
                <nous>regrettons</nous>
                <vous>regrettez</vous>
                <ils>regrettent</ils>
            </present>
            <imperative>
                <tu>regrette</tu>
                <nous>regrettons</nous>
                <vous>regrettez</vous>
            </imperative>
            <imperfect>
                <je>regrettais</je>
                <tu>regrettais</tu>
                <il>regrettait</il>
                <nous>regrettions</nous>
                <vous>regrettiez</vous>
                <ils>regrettaient</ils>
            </imperfect>
            <future>
                <je>regretterai</je>
                <tu>regretteras</tu>
                <il>regrettera</il>
                <nous>regretterons</nous>
                <vous>regretterez</vous>
                <ils>regretteront</ils>
            </future>
            <subjunctive>
                <je>regrette</je>
                <tu>regrettes</tu>
                <il>regrette</il>
                <nous>regrettions</nous>
                <vous>regrettiez</vous>
                <ils>regrettent</ils>
            </subjunctive>
            <conditional>
                <je>regretterais</je>
                <tu>regretterais</tu>
                <il>regretterait</il>
                <nous>regretterions</nous>
                <vous>regretteriez</vous>
                <ils>regretteraient</ils>
            </conditional>
        </verb>
    </verbs>
</dictionary>

=== alanapz/frtest/db/verbs/Baver.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE dictionary SYSTEM "verbs.dtd">
<dictionary>
<verbs>
<verb>
	<infinitive>baver</infinitive>
	<translation>to dribble</translation>
	<translation>leak</translation>
	<translation>(fam) to have a hard time</translation>
	<presentParticiple>bavant</presentParticiple>
	<pastParticiple>bavÃ©</pastParticiple>
	<present>
		<je>bave</je>
		<tu>baves</tu>
		<il>bave</il>
		<nous>bavons</nous>
		<vous>bavez</vous>
		<ils>bavent</ils>
	</present>
	<imperative>
		<tu>bave</tu>
		<nous>bavons</nous>
		<vous>bavez</vous>
	</imperative>
	<imperfect>
		<je>bavais</je>
		<tu>bavais</tu>
		<il>bavait</il>
		<nous>bavions</nous>
		<vous>baviez</vous>
		<ils>bavaient</ils>
	</imperfect>
	<future>
		<je>baverai</je>
		<tu>baveras</tu>
		<il>bavera</il>
		<nous>baverons</nous>
		<vous>baverez</vous>
		<ils>baveront</ils>
	</future>
	<subjunctive>
		<je>bave</je>
		<tu>baves</tu>
		<il>bave</il>
		<nous>bavions</nous>
		<vous>baviez</vous>
		<ils>bavent</ils>
	</subjunctive>
	<conditional>
		<je>baverais</je>
		<tu>baverais</tu>
		<il>baverait</il>
		<nous>baverions</nous>
		<vous>baveriez</vous>
		<ils>baveraient</ils>
	</conditional>
</verb>
</verbs>
</dictionary>
