=== alanapz/frtest/app/src/main/resources/verbs.dtd
<?xml version='1.0' encoding='UTF-8'?>
<!ELEMENT dictionary (verbs)*>
<!ELEMENT verbs (verb)*>
<!ELEMENT verb (infinitive, hAspire?, translation*, transitive?, irregular?, takesEtreInPerfect?, spellingChange?, stemChange?, presentParticiple?, pastParticiple?, pronominal?, present?, imperative?, imperfect?, future?, subjunctive?, conditional?)>
<!ELEMENT infinitive (#PCDATA)>
<!ELEMENT hAspire EMPTY>
<!ELEMENT translation (#PCDATA)>
<!ELEMENT transitive EMPTY>
<!ELEMENT important EMPTY>
<!ELEMENT commonplace EMPTY>
<!ELEMENT irregular EMPTY>
<!ELEMENT takesEtreInPerfect EMPTY>
<!ELEMENT spellingChange EMPTY>
<!ELEMENT stemChange EMPTY>
<!ELEMENT presentParticiple (#PCDATA)>
<!ELEMENT pastParticiple (#PCDATA)>
<!ELEMENT pronominal (translation+)>
<!ELEMENT present (je, tu, il, nous, vous, ils)>
<!ELEMENT imperative (tu, nous, vous)>
<!ELEMENT imperfect (je, tu, il, nous, vous, ils)>
<!ELEMENT future (je, tu, il, nous, vous, ils)>
<!ELEMENT subjunctive (je, tu, il, nous, vous, ils)>
<!ELEMENT conditional (je, tu, il, nous, vous, ils)>
<!ELEMENT je (#PCDATA)>
<!ELEMENT tu (#PCDATA)>
<!ELEMENT il (#PCDATA)>
<!ELEMENT nous (#PCDATA)>
<!ELEMENT vous (#PCDATA)>
<!ELEMENT ils (#PCDATA)>

=== alanapz/frtest/db/verbs/Consoler.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE dictionary SYSTEM "verbs.dtd">
<dictionary>
<verbs>
<verb>
	<infinitive>consoler</infinitive>
	<translation>to console</translation>
	<translation>soothe</translation>
	<presentParticiple>consolant</presentParticiple>
	<pastParticiple>consol√©</pastParticiple>
	<present>
		<je>console</je>
		<tu>consoles</tu>
		<il>console</il>
		<nous>consolons</nous>
		<vous>consolez</vous>
		<ils>consolent</ils>
	</present>
	<imperative>
		<tu>console</tu>
		<nous>consolons</nous>
		<vous>consolez</vous>
	</imperative>
	<imperfect>
		<je>consolais</je>
		<tu>consolais</tu>
		<il>consolait</il>
		<nous>consolions</nous>
		<vous>consoliez</vous>
		<ils>consolaient</ils>
	</imperfect>
	<future>
		<je>consolerai</je>
		<tu>consoleras</tu>
		<il>consolera</il>
		<nous>consolerons</nous>
		<vous>consolerez</vous>
		<ils>consoleront</ils>
	</future>
	<subjunctive>
		<je>console</je>
		<tu>consoles</tu>
		<il>console</il>
		<nous>consolions</nous>
		<vous>consoliez</vous>
		<ils>consolent</ils>
	</subjunctive>
	<conditional>
		<je>consolerais</je>
		<tu>consolerais</tu>
		<il>consolerait</il>
		<nous>consolerions</nous>
		<vous>consoleriez</vous>
		<ils>consoleraient</ils>
	</conditional>
</verb>
</verbs>
</dictionary>

=== alanapz/frtest/db/verbs/Perforer.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE dictionary SYSTEM "verbs.dtd">
<dictionary>
<verbs>
<verb>
	<infinitive>perforer</infinitive>
	<translation>to perforate</translation>
	<presentParticiple>perforant</presentParticiple>
	<pastParticiple>perfor√©</pastParticiple>
	<present>
		<je>perfore</je>
		<tu>perfores</tu>
		<il>perfore</il>
		<nous>perforons</nous>
		<vous>perforez</vous>
		<ils>perforent</ils>
	</present>
	<imperative>
		<tu>perfore</tu>
		<nous>perforons</nous>
		<vous>perforez</vous>
	</imperative>
	<imperfect>
		<je>perforais</je>
		<tu>perforais</tu>
		<il>perforait</il>
		<nous>perforions</nous>
		<vous>perforiez</vous>
		<ils>perforaient</ils>
	</imperfect>
	<future>
		<je>perforerai</je>
		<tu>perforeras</tu>
		<il>perforera</il>
		<nous>perforerons</nous>
		<vous>perforerez</vous>
		<ils>perforeront</ils>
	</future>
	<subjunctive>
		<je>perfore</je>
		<tu>perfores</tu>
		<il>perfore</il>
		<nous>perforions</nous>
		<vous>perforiez</vous>
		<ils>perforent</ils>
	</subjunctive>
	<conditional>
		<je>perforerais</je>
		<tu>perforerais</tu>
		<il>perforerait</il>
		<nous>perforerions</nous>
		<vous>perforeriez</vous>
		<ils>perforeraient</ils>
	</conditional>
</verb>
</verbs>
</dictionary>

=== alanapz/frtest/db/verbs/Bronzer.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE dictionary SYSTEM "verbs.dtd">
<dictionary>
<verbs>
<verb>
	<infinitive>bronzer</infinitive>
	<translation>to tan</translation>
	<presentParticiple>bronzant</presentParticiple>
	<pastParticiple>bronz√©</pastParticiple>
	<present>
		<je>bronze</je>
		<tu>bronzes</tu>
		<il>bronze</il>
		<nous>bronzons</nous>
		<vous>bronzez</vous>
		<ils>bronzent</ils>
	</present>
	<imperative>
		<tu>bronze</tu>
		<nous>bronzons</nous>
		<vous>bronzez</vous>
	</imperative>
	<imperfect>
		<je>bronzais</je>
		<tu>bronzais</tu>
		<il>bronzait</il>
		<nous>bronzions</nous>
		<vous>bronziez</vous>
		<ils>bronzaient</ils>
	</imperfect>
	<future>
		<je>bronzerai</je>
		<tu>bronzeras</tu>
		<il>bronzera</il>
		<nous>bronzerons</nous>
		<vous>bronzerez</vous>
		<ils>bronzeront</ils>
	</future>
	<subjunctive>
		<je>bronze</je>
		<tu>bronzes</tu>
		<il>bronze</il>
		<nous>bronzions</nous>
		<vous>bronziez</vous>
		<ils>bronzent</ils>
	</subjunctive>
	<conditional>
		<je>bronzerais</je>
		<tu>bronzerais</tu>
		<il>bronzerait</il>
		<nous>bronzerions</nous>
		<vous>bronzeriez</vous>
		<ils>bronzeraient</ils>
	</conditional>
</verb>
</verbs>
</dictionary>

=== alanapz/frtest/db/verbs/Fureter.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE dictionary SYSTEM "verbs.dtd">
<dictionary>
<verbs>
<verb>
	<infinitive>fureter</infinitive>
	<translation>to rummage</translation>
	<translation>nose around</translation>
	<stemChange />
	<presentParticiple>furetant</presentParticiple>
	<pastParticiple>fureté</pastParticiple>
	<present>
		<je>furète</je>
		<tu>furètes</tu>
		<il>furète</il>
		<nous>furetons</nous>
		<vous>furetez</vous>
		<ils>furètent</ils>
	</present>
	<imperative>
		<tu>furète</tu>
		<nous>furetons</nous>
		<vous>furetez</vous>
	</imperative>
	<imperfect>
		<je>furetais</je>
		<tu>furetais</tu>
		<il>furetait</il>
		<nous>furetions</nous>
		<vous>furetiez</vous>
		<ils>furetaient</ils>
	</imperfect>
	<future>
		<je>furèterai</je>
		<tu>furèteras</tu>
		<il>furètera</il>
		<nous>furèterons</nous>
		<vous>furèterez</vous>
		<ils>furèteront</ils>
	</future>
	<subjunctive>
		<je>furète</je>
		<tu>furètes</tu>
		<il>furète</il>
		<nous>furetions</nous>
		<vous>furetiez</vous>
		<ils>furètent</ils>
	</subjunctive>
	<conditional>
		<je>furèterais</je>
		<tu>furèterais</tu>
		<il>furèterait</il>
		<nous>furèterions</nous>
		<vous>furèteriez</vous>
		<ils>furèteraient</ils>
	</conditional>
</verb>
</verbs>
</dictionary>

=== alanapz/frtest/db/verbs/Tricher.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE dictionary SYSTEM "verbs.dtd">
<dictionary>
<verbs>
<verb>
	<infinitive>tricher</infinitive>
	<translation>to trick</translation>
	<translation>cheat</translation>
	<presentParticiple>trichant</presentParticiple>
	<pastParticiple>trich√©</pastParticiple>
	<present>
		<je>triche</je>
		<tu>triches</tu>
		<il>triche</il>
		<nous>trichons</nous>
		<vous>trichez</vous>
		<ils>trichent</ils>
	</present>
	<imperative>
		<tu>triche</tu>
		<nous>trichons</nous>
		<vous>trichez</vous>
	</imperative>
	<imperfect>
		<je>trichais</je>
		<tu>trichais</tu>
		<il>trichait</il>
		<nous>trichions</nous>
		<vous>trichiez</vous>
		<ils>trichaient</ils>
	</imperfect>
	<future>
		<je>tricherai</je>
		<tu>tricheras</tu>
		<il>trichera</il>
		<nous>tricherons</nous>
		<vous>tricherez</vous>
		<ils>tricheront</ils>
	</future>
	<subjunctive>
		<je>triche</je>
		<tu>triches</tu>
		<il>triche</il>
		<nous>trichions</nous>
		<vous>trichiez</vous>
		<ils>trichent</ils>
	</subjunctive>
	<conditional>
		<je>tricherais</je>
		<tu>tricherais</tu>
		<il>tricherait</il>
		<nous>tricherions</nous>
		<vous>tricheriez</vous>
		<ils>tricheraient</ils>
	</conditional>
</verb>
</verbs>
</dictionary>

=== alanapz/frtest/db/verbs/Actualiser.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE dictionary SYSTEM "verbs.dtd">
<dictionary>
<verbs>
<verb>
	<infinitive>actualiser</infinitive>
	<translation>to update</translation>
	<translation>actualize</translation>
	<presentParticiple>actualisant</presentParticiple>
	<pastParticiple>actualis√©</pastParticiple>
	<present>
		<je>actualise</je>
		<tu>actualises</tu>
		<il>actualise</il>
		<nous>actualisons</nous>
		<vous>actualisez</vous>
		<ils>actualisent</ils>
	</present>
	<imperative>
		<tu>actualise</tu>
		<nous>actualisons</nous>
		<vous>actualisez</vous>
	</imperative>
	<imperfect>
		<je>actualisais</je>
		<tu>actualisais</tu>
		<il>actualisait</il>
		<nous>actualisions</nous>
		<vous>actualisiez</vous>
		<ils>actualisaient</ils>
	</imperfect>
	<future>
		<je>actualiserai</je>
		<tu>actualiseras</tu>
		<il>actualisera</il>
		<nous>actualiserons</nous>
		<vous>actualiserez</vous>
		<ils>actualiseront</ils>
	</future>
	<subjunctive>
		<je>actualise</je>
		<tu>actualises</tu>
		<il>actualise</il>
		<nous>actualisions</nous>
		<vous>actualisiez</vous>
		<ils>actualisent</ils>
	</subjunctive>
	<conditional>
		<je>actualiserais</je>
		<tu>actualiserais</tu>
		<il>actualiserait</il>
		<nous>actualiserions</nous>
		<vous>actualiseriez</vous>
		<ils>actualiseraient</ils>
	</conditional>
</verb>
</verbs>
</dictionary>

=== alanapz/frtest/db/verbs/Guider.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE dictionary SYSTEM "verbs.dtd">
<dictionary>
<verbs>
<verb>
	<infinitive>guider</infinitive>
	<translation>to guide</translation>
	<presentParticiple>guidant</presentParticiple>
	<pastParticiple>guidÃ©</pastParticiple>
	<present>
		<je>guide</je>
		<tu>guides</tu>
		<il>guide</il>
		<nous>guidons</nous>
		<vous>guidez</vous>
		<ils>guident</ils>
	</present>
	<imperative>
		<tu>guide</tu>
		<nous>guidons</nous>
		<vous>guidez</vous>
	</imperative>
	<imperfect>
		<je>guidais</je>
		<tu>guidais</tu>
		<il>guidait</il>
		<nous>guidions</nous>
		<vous>guidiez</vous>
		<ils>guidaient</ils>
	</imperfect>
	<future>
		<je>guiderai</je>
		<tu>guideras</tu>
		<il>guidera</il>
		<nous>guiderons</nous>
		<vous>guiderez</vous>
		<ils>guideront</ils>
	</future>
	<subjunctive>
		<je>guide</je>
		<tu>guides</tu>
		<il>guide</il>
		<nous>guidions</nous>
		<vous>guidiez</vous>
		<ils>guident</ils>
	</subjunctive>
	<conditional>
		<je>guiderais</je>
		<tu>guiderais</tu>
		<il>guiderait</il>
		<nous>guiderions</nous>
		<vous>guideriez</vous>
		<ils>guideraient</ils>
	</conditional>
</verb>
</verbs>
</dictionary>

=== alanapz/frtest/db/verbs/Frémir.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE dictionary SYSTEM "verbs.dtd">
<dictionary>
<verbs>
<verb>
	<infinitive>frémir</infinitive>
	<translation>to shudder</translation>
	<presentParticiple>frémissant</presentParticiple>
	<pastParticiple>frémi</pastParticiple>
	<present>
		<je>frémis</je>
		<tu>frémis</tu>
		<il>frémit</il>
		<nous>frémissons</nous>
		<vous>frémissez</vous>
		<ils>frémissent</ils>
	</present>
	<imperative>
		<tu>frémis</tu>
		<nous>frémissons</nous>
		<vous>frémissez</vous>
	</imperative>
	<imperfect>
		<je>frémissais</je>
		<tu>frémissais</tu>
		<il>frémissait</il>
		<nous>frémissions</nous>
		<vous>frémissiez</vous>
		<ils>frémissaient</ils>
	</imperfect>
	<future>
		<je>frémirai</je>
		<tu>frémiras</tu>
		<il>frémira</il>
		<nous>frémirons</nous>
		<vous>frémirez</vous>
		<ils>frémiront</ils>
	</future>
	<subjunctive>
		<je>frémisse</je>
		<tu>frémisses</tu>
		<il>frémisse</il>
		<nous>frémissions</nous>
		<vous>frémissiez</vous>
		<ils>frémissent</ils>
	</subjunctive>
	<conditional>
		<je>frémirais</je>
		<tu>frémirais</tu>
		<il>frémirait</il>
		<nous>frémirions</nous>
		<vous>frémiriez</vous>
		<ils>frémiraient</ils>
	</conditional>
</verb>
</verbs>
</dictionary>
